<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SARes</AssemblyName>

    <!-- publish defaults -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2651.64" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
    <PackageReference Include="SharpCompress" Version="0.38.0" />
    <PackageReference Include="Markdig" Version="0.30.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- Exclude internal tooling projects from the WPF app build. -->
  <ItemGroup>
    <Compile Remove="tools\**\*.cs" />
  </ItemGroup>

</Project>
