<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tools\\**\\*.cs" />
    <None Remove="tools\\**\\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.72.0.3966" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\PainRadar.Core\\PainRadar.Core.csproj" />
  </ItemGroup>

</Project>
